solana-keygen new -s --no-bip39-passphrase -o user101_account.json && solana-keygen new -s --no-bip39-passphrase -o user101_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user102_account.json && solana-keygen new -s --no-bip39-passphrase -o user102_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user103_account.json && solana-keygen new -s --no-bip39-passphrase -o user103_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user104_account.json && solana-keygen new -s --no-bip39-passphrase -o user104_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user105_account.json && solana-keygen new -s --no-bip39-passphrase -o user105_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user106_account.json && solana-keygen new -s --no-bip39-passphrase -o user106_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user107_account.json && solana-keygen new -s --no-bip39-passphrase -o user107_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user108_account.json && solana-keygen new -s --no-bip39-passphrase -o user108_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user109_account.json && solana-keygen new -s --no-bip39-passphrase -o user109_wallet.json

solana-keygen new -s --no-bip39-passphrase -o user110_account.json && solana-keygen new -s --no-bip39-passphrase -o user110_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user111_account.json && solana-keygen new -s --no-bip39-passphrase -o user111_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user112_account.json && solana-keygen new -s --no-bip39-passphrase -o user112_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user113_account.json && solana-keygen new -s --no-bip39-passphrase -o user113_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user114_account.json && solana-keygen new -s --no-bip39-passphrase -o user114_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user115_account.json && solana-keygen new -s --no-bip39-passphrase -o user115_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user116_account.json && solana-keygen new -s --no-bip39-passphrase -o user116_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user117_account.json && solana-keygen new -s --no-bip39-passphrase -o user117_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user118_account.json && solana-keygen new -s --no-bip39-passphrase -o user118_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user119_account.json && solana-keygen new -s --no-bip39-passphrase -o user119_wallet.json

solana-keygen new -s --no-bip39-passphrase -o user120_account.json && solana-keygen new -s --no-bip39-passphrase -o user120_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user121_account.json && solana-keygen new -s --no-bip39-passphrase -o user121_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user122_account.json && solana-keygen new -s --no-bip39-passphrase -o user122_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user123_account.json && solana-keygen new -s --no-bip39-passphrase -o user123_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user124_account.json && solana-keygen new -s --no-bip39-passphrase -o user124_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user125_account.json && solana-keygen new -s --no-bip39-passphrase -o user125_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user126_account.json && solana-keygen new -s --no-bip39-passphrase -o user126_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user127_account.json && solana-keygen new -s --no-bip39-passphrase -o user127_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user128_account.json && solana-keygen new -s --no-bip39-passphrase -o user128_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user129_account.json && solana-keygen new -s --no-bip39-passphrase -o user129_wallet.json

solana-keygen new -s --no-bip39-passphrase -o user130_account.json && solana-keygen new -s --no-bip39-passphrase -o user130_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user131_account.json && solana-keygen new -s --no-bip39-passphrase -o user131_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user132_account.json && solana-keygen new -s --no-bip39-passphrase -o user132_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user133_account.json && solana-keygen new -s --no-bip39-passphrase -o user133_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user134_account.json && solana-keygen new -s --no-bip39-passphrase -o user134_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user135_account.json && solana-keygen new -s --no-bip39-passphrase -o user135_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user136_account.json && solana-keygen new -s --no-bip39-passphrase -o user136_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user137_account.json && solana-keygen new -s --no-bip39-passphrase -o user137_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user138_account.json && solana-keygen new -s --no-bip39-passphrase -o user138_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user139_account.json && solana-keygen new -s --no-bip39-passphrase -o user139_wallet.json

solana-keygen new -s --no-bip39-passphrase -o user140_account.json && solana-keygen new -s --no-bip39-passphrase -o user140_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user141_account.json && solana-keygen new -s --no-bip39-passphrase -o user141_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user142_account.json && solana-keygen new -s --no-bip39-passphrase -o user142_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user143_account.json && solana-keygen new -s --no-bip39-passphrase -o user143_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user144_account.json && solana-keygen new -s --no-bip39-passphrase -o user144_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user145_account.json && solana-keygen new -s --no-bip39-passphrase -o user145_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user146_account.json && solana-keygen new -s --no-bip39-passphrase -o user146_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user147_account.json && solana-keygen new -s --no-bip39-passphrase -o user147_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user148_account.json && solana-keygen new -s --no-bip39-passphrase -o user148_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user149_account.json && solana-keygen new -s --no-bip39-passphrase -o user149_wallet.json

solana-keygen new -s --no-bip39-passphrase -o user150_account.json && solana-keygen new -s --no-bip39-passphrase -o user150_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user151_account.json && solana-keygen new -s --no-bip39-passphrase -o user151_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user152_account.json && solana-keygen new -s --no-bip39-passphrase -o user152_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user153_account.json && solana-keygen new -s --no-bip39-passphrase -o user153_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user154_account.json && solana-keygen new -s --no-bip39-passphrase -o user154_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user155_account.json && solana-keygen new -s --no-bip39-passphrase -o user155_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user156_account.json && solana-keygen new -s --no-bip39-passphrase -o user156_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user157_account.json && solana-keygen new -s --no-bip39-passphrase -o user157_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user158_account.json && solana-keygen new -s --no-bip39-passphrase -o user158_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user159_account.json && solana-keygen new -s --no-bip39-passphrase -o user159_wallet.json

solana-keygen new -s --no-bip39-passphrase -o user160_account.json && solana-keygen new -s --no-bip39-passphrase -o user160_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user161_account.json && solana-keygen new -s --no-bip39-passphrase -o user161_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user162_account.json && solana-keygen new -s --no-bip39-passphrase -o user162_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user163_account.json && solana-keygen new -s --no-bip39-passphrase -o user163_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user164_account.json && solana-keygen new -s --no-bip39-passphrase -o user164_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user165_account.json && solana-keygen new -s --no-bip39-passphrase -o user165_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user166_account.json && solana-keygen new -s --no-bip39-passphrase -o user166_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user167_account.json && solana-keygen new -s --no-bip39-passphrase -o user167_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user168_account.json && solana-keygen new -s --no-bip39-passphrase -o user168_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user169_account.json && solana-keygen new -s --no-bip39-passphrase -o user169_wallet.json

solana-keygen new -s --no-bip39-passphrase -o user170_account.json && solana-keygen new -s --no-bip39-passphrase -o user170_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user171_account.json && solana-keygen new -s --no-bip39-passphrase -o user171_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user172_account.json && solana-keygen new -s --no-bip39-passphrase -o user172_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user173_account.json && solana-keygen new -s --no-bip39-passphrase -o user173_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user174_account.json && solana-keygen new -s --no-bip39-passphrase -o user174_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user175_account.json && solana-keygen new -s --no-bip39-passphrase -o user175_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user176_account.json && solana-keygen new -s --no-bip39-passphrase -o user176_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user177_account.json && solana-keygen new -s --no-bip39-passphrase -o user177_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user178_account.json && solana-keygen new -s --no-bip39-passphrase -o user178_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user179_account.json && solana-keygen new -s --no-bip39-passphrase -o user179_wallet.json

solana-keygen new -s --no-bip39-passphrase -o user180_account.json && solana-keygen new -s --no-bip39-passphrase -o user180_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user181_account.json && solana-keygen new -s --no-bip39-passphrase -o user181_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user182_account.json && solana-keygen new -s --no-bip39-passphrase -o user182_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user183_account.json && solana-keygen new -s --no-bip39-passphrase -o user183_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user184_account.json && solana-keygen new -s --no-bip39-passphrase -o user184_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user185_account.json && solana-keygen new -s --no-bip39-passphrase -o user185_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user186_account.json && solana-keygen new -s --no-bip39-passphrase -o user186_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user187_account.json && solana-keygen new -s --no-bip39-passphrase -o user187_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user188_account.json && solana-keygen new -s --no-bip39-passphrase -o user188_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user189_account.json && solana-keygen new -s --no-bip39-passphrase -o user189_wallet.json

solana-keygen new -s --no-bip39-passphrase -o user190_account.json && solana-keygen new -s --no-bip39-passphrase -o user190_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user191_account.json && solana-keygen new -s --no-bip39-passphrase -o user191_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user192_account.json && solana-keygen new -s --no-bip39-passphrase -o user192_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user193_account.json && solana-keygen new -s --no-bip39-passphrase -o user193_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user194_account.json && solana-keygen new -s --no-bip39-passphrase -o user194_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user195_account.json && solana-keygen new -s --no-bip39-passphrase -o user195_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user196_account.json && solana-keygen new -s --no-bip39-passphrase -o user196_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user197_account.json && solana-keygen new -s --no-bip39-passphrase -o user197_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user198_account.json && solana-keygen new -s --no-bip39-passphrase -o user198_wallet.json
solana-keygen new -s --no-bip39-passphrase -o user199_account.json && solana-keygen new -s --no-bip39-passphrase -o user199_wallet.json

solana-keygen new -s --no-bip39-passphrase -o user200_account.json && solana-keygen new -s --no-bip39-passphrase -o user200_wallet.json
